
import type { Game } from './types';

export const games: Game[] = [
  {
    id: '1',
    title: 'Core Ball',
    description: 'A simple and addictive game about timing and precision. Can you attach all the balls to the core without them colliding?',
    imageUrl: 'https://iili.io/KCqdtef.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbwuWPuF8N5zZDqvwEqA35knRMPA6o3QtCnBYuf0kbWVtTA99viuRzJ6FkfhC5yedotu/exec',
    tags: ['arcade', 'puzzle', 'skill', 'minimalist'],
    featured: true,
  },
  {
    id: '3',
    title: 'Monkey Mart',
    description: 'Manage your own supermarket, stock shelves, and serve customers in this fun management game.',
    imageUrl: 'https://play-lh.googleusercontent.com/rWReIdyvDaYJPeOxn7hbC0b-96ixGpQKM_EndiQa3SUME8TtI_rNUcI4qsw5teK9mqk',
    gameUrl: 'https://monkeymart-unblocked.com/game',
    tags: ['management', 'simulation', 'casual', 'strategy'],
    featured: true,
  },
  {
    id: '4',
    title: 'Cluster Rush',
    description: 'Jump from truck to truck in a high-speed, high-stakes game of agility and timing.',
    imageUrl: 'https://rocketgames.imgix.net/uploads/games/c/cluster-rush/cluster-rush.5c9f51.png?auto=format,compress,enhance&w=314&dpr=1',
    gameUrl: 'https://script.google.com/macros/s/AKfycbw6e8fflbfydV7kom5id09nKaM6ix0hLlXHbs3XHOnxzrndUgPtHUHENrwKomI2Hpk3/exec',
    tags: ['action', 'platformer', '3d', 'fast-paced'],
    featured: false,
  },
  {
    id: '6',
    title: 'Car Crash',
    description: 'A realistic car crash simulator. Test the limits of destruction.',
    imageUrl: 'https://iili.io/KBcIBea.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbwnHhMofGNjZt4xEn7HZJTUBs2klhlPV7mk4-_LGHESeYIFmtQiGn0gr3VT52AZna0U/exec',
    tags: ['simulation', 'driving', 'physics'],
    featured: false,
  },
  {
    id: '7',
    title: 'FNAF',
    description: "Survive five nights at Freddy Fazbear's Pizzeria in this terrifying horror game.",
    imageUrl: 'https://iili.io/KBciryx.jpg',
    gameUrl: "https://script.google.com/macros/s/AKfycbxJNtrKTWPCSIo9tOqq53G2xqoQCIPDTYUsVOT79Eqk8I7C5cQkGdDnj0jzlNHa7bvs3g/exec",
    tags: ['horror', 'survival', 'point-and-click'],
    featured: false,
  },
  {
    id: '8',
    title: 'Idle Breakout',
    description: 'Break blocks, earn money, and upgrade your balls in this addictive idle game.',
    imageUrl: 'https://iili.io/KBcDYTG.png',
    gameUrl: 'https://embeddr.rhw.one/embed#https://idle-breakout.neocities.org/',
    tags: ['idle', 'arcade', 'clicker', 'breakout'],
    featured: true,
  },
  {
    id: '9',
    title: 'Drift Boss',
    description: 'Show off your driving skills by drifting through tight corners.',
    imageUrl: 'https://iili.io/KBlF5Xt.jpg',
    gameUrl: 'https://script.google.com/macros/s/AKfycbwAOi2tPbjzeWDkigfZMIPEGubYxz2la_qjxJyydNZyjwgbqsv9mv05g7tdmLHdvdaw/exec',
    tags: ['driving', 'drifting', 'skill', 'arcade'],
    featured: false,
  },
  {
    id: '10',
    title: 'CSGO Clicker',
    description: 'Click to open cases and collect rare items in this addictive clicking game.',
    imageUrl: 'https://iili.io/KB02cX9.webp',
    gameUrl: 'https://script.google.com/macros/s/AKfycbwKKRujNfvv7u1c2DqAjTAe72Y0zN2BZGJPeZprhS7GpfvW1kN_MQs-_ACFOfJ_EBhO1w/exec',
    tags: ['clicker', 'simulation', 'idle'],
    featured: false,
  },
  {
    id: '11',
    title: 'Cookie Clicker',
    description: 'An addictive idle game where you click a cookie to make more cookies. Upgrade your production to create a cookie empire.',
    imageUrl: 'https://iili.io/KCqz1Jp.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbxGM35J29NkO-2LYjxWj_cA9IUaaXypkUy-LqXyLRbGTz0R6lXmAEapz1STN1jlTIRavw/exec',
    tags: ['clicker', 'idle', 'casual', 'addictive'],
    featured: false,
  },
  {
    id: '12',
    title: 'Slope',
    description: 'An endless runner game where you control a ball down a series of slopes.',
    imageUrl: 'https://iili.io/KCq7Xyv.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/slope/index.html',
    tags: ['endless runner', '3d', 'skill', 'arcade'],
    featured: false,
  },
  {
    id: '13',
    title: 'Clash Royale',
    description: 'A real-time, head-to-head battle game set in the Clash Universe.',
    imageUrl: 'https://iili.io/KRjdpft.png',
    gameUrl: 'https://art.fullsusmtb.org/html/clash_royale/',
    tags: ['strategy', 'real-time', 'card game', 'multiplayer'],
    featured: false,
  },
  {
    id: '14',
    title: 'Minecraft',
    description: 'A sandbox game about placing blocks and going on adventures.',
    imageUrl: 'https://iili.io/KRjREPe.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/minecraft/',
    tags: ['sandbox', 'survival', 'building', 'open-world'],
    featured: false,
  },
  {
    id: '15',
    title: 'Steal a Brainrot',
    description: 'Steal a Brainrot is a Roblox game where players steal and collect quirky meme-like characters while protecting their own from being taken.',
    imageUrl: 'https://iili.io/KRjlVl1.md.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbxJalyip_ETy_kolDAlSVxdcnLtn16P6gIoJ5kDwt1abHFX32SUJEOLCWU31veTffv2/exec',
    tags: ['puzzle', 'humor', 'casual', 'roblox'],
    featured: true,
  },
  {
    id: '16',
    title: 'Grow a Garden',
    description: 'Cultivate your own virtual garden, plant seeds, water them, and watch them grow into beautiful flowers and plants.',
    imageUrl: 'https://iili.io/KRjVNbn.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/steal_a_brainrot/index.html',
    tags: ['simulation', 'gardening', 'casual', 'relaxing', 'roblox'],
    featured: false,
  },
  {
    id: '17',
    title: 'Squid Games',
    description: 'Survive a series of deadly mini-games inspired by the popular show.',
    imageUrl: 'https://a.silvergames.com/j/b/squid-game-mini-games-online.jpg',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/squid_game_2_mini_games/index.html',
    tags: ['action', 'survival', 'mini-games'],
    featured: false,
  },
  {
    id: '18',
    title: 'COD Zombies Portable',
    description: 'Survive waves of zombies in this portable version of the classic game mode.',
    imageUrl: 'https://iili.io/KRwCPIe.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/cod_zombies_portable/index.html',
    tags: ['action', 'survival', 'zombies', 'shooter'],
    featured: false,
  },
  {
    id: '19',
    title: 'Block Blast',
    description: 'A challenging puzzle game where you fit blocks together to clear lines.',
    imageUrl: 'https://iili.io/KRw7EJa.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/blocky_puzzle/index.html',
    tags: ['puzzle', 'casual', 'strategy', 'block'],
    featured: false,
  },
  {
    id: '20',
    title: 'Poly Track',
    description: 'A fast-paced, futuristic racing game where you navigate through a low-poly world.',
    imageUrl: 'https://1games.io/data/image/game/polytrack/banner/poly-track.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbzuhv-wKflC3QgCI_d8xsy90ngRlqgKj-qfICMuzhimGuYwWXFI5tPWwwfjrYk-biJu/exec',
    tags: ['racing', '3d', 'endless-runner', 'skill'],
    featured: false,
  },
  {
    id: '21',
    title: 'Rocket Soccer Derby',
    description: 'Combine soccer with rocket-powered cars in this high-octane multiplayer game.',
    imageUrl: 'https://iili.io/KRkqE6G.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/rocket_soccer_derby/index.html',
    tags: ['sports', 'driving', 'multiplayer', 'action'],
    featured: false,
  },
  {
    id: '22',
    title: 'Moto X3M',
    description: 'A fun and challenging bike racing game with crazy stunts and obstacles.',
    imageUrl: 'https://img.poki-cdn.com/cdn-cgi/image/q=78,scq=50,width=314,height=314,fit=cover,f=auto/2c6d5a46cdbceada277c870ce1c389ee/moto-x3m.jpg',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/moto_x3m_3/index.html',
    tags: ['racing', 'stunts', 'bike', 'physics'],
    featured: false,
  },
  {
    id: '23',
    title: 'Rooftop Snipers',
    description: 'A chaotic physics-based shooting game. Try to knock your opponent off the roof.',
    imageUrl: 'https://iili.io/KRNoRQn.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/rooftop_snipers/index.html',
    tags: ['action', 'physics', '2-player', 'shooting'],
    featured: false,
  },
  {
    id: '24',
    title: 'Snow Rider 3D',
    description: 'Ride your sled down a snowy mountain, avoid obstacles, and collect gifts.',
    imageUrl: 'https://iili.io/KRN0Zhb.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbw5Z-Ryg_JfIIDYH7pzzPKXlr2tN0HCw-tT_ZvxBGDPsDDY41ewPVneVeLzelfpnBab/exec',
    tags: ['racing', '3d', 'winter', 'skill'],
    featured: false,
  },
  {
    id: '25',
    title: 'Retro Bowl',
    description: 'Live out your dream as an NFL quarterback in this retro-style football game. Manage your team, call the plays, and lead them to victory.',
    imageUrl: 'https://iili.io/KRNN4e4.png',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/retro_bowl/index.html',
    tags: ['sports', 'football', 'retro', 'strategy'],
    featured: false,
  },
  {
    id: '26',
    title: 'Time Shooter 3 SWAT',
    description: 'A tactical shooter where time only moves when you do. Plan your moves carefully to take down enemies.',
    imageUrl: 'https://iili.io/KROzw9R.jpg',
    gameUrl: 'https://maddox.page/basic-ruffle-player/html/time_shooter_swat/index.html',
    tags: ['action', 'shooter', 'strategy', 'time-bending'],
    featured: false,
  }
];
