
import type { Game } from './types';

export const games: Game[] = [
  {
    id: '1',
    title: 'Core Ball',
    description: 'A simple and addictive game about timing and precision. Can you attach all the balls to the core without them colliding?',
    imageUrl: 'https://iili.io/KCqdtef.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbyob7HxkiW2e0yT22QRiejnA_alDdUkPnrNirnvCX1HYPriGPR6_GZ2i1RsglPytlFo/exec',
    tags: ['arcade', 'puzzle', 'skill', 'minimalist'],
    featured: true,
  },
  {
    id: '3',
    title: 'Monkey Mart',
    description: 'Manage your own supermarket, stock shelves, and serve customers in this fun management game.',
    imageUrl: 'https://play-lh.googleusercontent.com/rWReIdyvDaYJPeOxn7hbC0b-96ixGpQKM_EndiQa3SUME8TtI_rNUcI4qsw5teK9mqk',
    gameUrl: 'https://monkeymart-unblocked.com/game',
    tags: ['management', 'simulation', 'casual', 'strategy'],
    featured: true,
  },
  {
    id: '4',
    title: 'Cluster Rush',
    description: 'Jump from truck to truck in a high-speed, high-stakes game of agility and timing.',
    imageUrl: 'https://rocketgames.imgix.net/uploads/games/c/cluster-rush/cluster-rush.5c9f51.png?auto=format,compress,enhance&w=314&dpr=1',
    gameUrl: 'https://script.google.com/macros/s/AKfycbw6e8fflbfydV7kom5id09nKaM6ix0hLlXHbs3XHOnxzrndUgPtHUHENrwKomI2Hpk3/exec',
    tags: ['action', 'platformer', '3d', 'fast-paced'],
    featured: false,
  },
  {
    id: '5',
    title: 'Minecraft',
    description: 'A sandbox game where you can build anything you can imagine. Explore, survive, and create.',
    imageUrl: 'https://iili.io/KCqB1El.png',
    gameUrl: 'https://embeddr.rhw.one/embed#https://eaglercraft.com/mc/1.8.8',
    tags: ['sandbox', 'survival', 'building', 'adventure'],
    featured: true,
  },
  {
    id: '6',
    title: 'Car Crash',
    description: 'A realistic car crash simulator. Test the limits of destruction.',
    imageUrl: 'https://iili.io/KBcIBea.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbwnHhMofGNjZt4xEn7HZJTUBs2klhlPV7mk4-_LGHESeYIFmtQiGn0gr3VT52AZna0U/exec',
    tags: ['simulation', 'driving', 'physics'],
    featured: false,
  },
  {
    id: '7',
    title: 'FNAF',
    description: "Survive five nights at Freddy Fazbear's Pizzeria in this terrifying horror game.",
    imageUrl: 'https://iili.io/KBciryx.jpg',
    gameUrl: 'https://embeddr.rhw.one/embed#https://wellsousaaa.github.io/Five-Nights-at-Freddys-Web/',
    tags: ['horror', 'survival', 'point-and-click'],
    featured: false,
  },
  {
    id: '8',
    title: 'Idle Breakout',
    description: 'Break blocks, earn money, and upgrade your balls in this addictive idle game.',
    imageUrl: 'https://iili.io/KBcDYTG.png',
    gameUrl: 'https://embeddr.rhw.one/embed#https://idle-breakout.neocities.org/',
    tags: ['idle', 'arcade', 'clicker', 'breakout'],
    featured: true,
  },
  {
    id: '9',
    title: 'Drift Boss',
    description: 'Show off your driving skills by drifting through tight corners.',
    imageUrl: 'https://iili.io/KBlF5Xt.jpg',
    gameUrl: 'https://embeddr.rhw.one/embed#https://cdn-factory.marketjs.com/en/drift-boss/index.html',
    tags: ['driving', 'drifting', 'skill', 'arcade'],
    featured: false,
  },
  {
    id: '10',
    title: 'Case Clicker',
    description: 'Click to open cases and collect rare items in this addictive clicking game.',
    imageUrl: 'https://iili.io/KB02cX9.webp',
    gameUrl: 'https://embeddr.rhw.one/embed#https://mtsl.dk/csgo/',
    tags: ['clicker', 'simulation', 'idle'],
    featured: false,
  },
  {
    id: '11',
    title: 'Cookie Clicker',
    description: 'An addictive idle game where you click a cookie to make more cookies. Upgrade your production to create a cookie empire.',
    imageUrl: 'https://i.imgur.com/DcTG9OS.png',
    gameUrl: 'https://script.google.com/macros/s/AKfycbxGM35J29NkO-2LYjxWj_cA9IUaaXypkUy-LqXyLRbGTz0R6lXmAEapz1STN1jlTIRavw/exec',
    tags: ['clicker', 'idle', 'casual', 'addictive'],
    featured: false,
  },
  {
    id: '12',
    title: 'Slope',
    description: 'An endless runner game where you control a ball down a series of slopes.',
    imageUrl: 'https://i.imgur.com/dIXzNL7.jpeg',
    gameUrl: 'https://embeddr.rhw.one/embed#https://azgames.io/game/slope/',
    tags: ['endless runner', '3d', 'skill', 'arcade'],
    featured: false,
  }
];
