
import type { Proxy } from './types';

export const proxys: Proxy[] = [
  {
    id: '1',
    title: 'Shadow',
    description: 'A proxy service for browsing the web securely and anonymously.',
    imageUrl: 'https://iili.io/K1ep1ob.png',
    proxyUrl: 'https://education.hornburst.com/',
    tags: ['utility', 'security', 'privacy'],
    featured: true,
  },
  {
    id: '2',
    title: 'Froggies Arcade V4',
    description: 'An arcade of web games and apps, accessible through a proxy.',
    imageUrl: 'https://iili.io/K1kH8ib.png',
    proxyUrl: 'https://directory.leeschoolsk12.org/',
    tags: ['games', 'entertainment'],
    featured: false,
  },
  {
    id: '3',
    title: 'PeteZah',
    description: 'A versatile proxy for accessing a wide range of online content.',
    imageUrl: 'https://iili.io/K1kFfu2.png',
    proxyUrl: 'https://english.jobvn.com/',
    tags: ['utility', 'web-access'],
    featured: false,
  },
  {
    id: '4',
    title: 'Ajh’s Vault',
    description: 'A secure vault for your browsing needs, keeping your activity private.',
    imageUrl: 'https://iili.io/K1kqpRf.png',
    proxyUrl: 'https://ajh.btc4animals.com/',
    tags: ['security', 'privacy'],
    featured: true,
  },
  {
    id: '5',
    title: 'Truffled',
    description: 'A fast and reliable proxy service with a focus on performance.',
    imageUrl: 'https://iili.io/K1kzEKB.png',
    proxyUrl: 'https://truffled.lol.cdn.cloudflare.net/',
    tags: ['utility', 'fast'],
    featured: false,
  },
  {
    id: '6',
    title: 'UniUB v4',
    description: 'The fourth version of the universal unblocker proxy service.',
    imageUrl: 'https://iili.io/K1kRBEv.png',
    proxyUrl: 'https://oliverloves.food.cdn.cloudflare.net/',
    tags: ['unblocker', 'utility'],
    featured: false,
  },
  {
    id: '7',
    title: 'Dogeub',
    description: 'A proxy service with a friendly interface and reliable performance.',
    imageUrl: 'https://iili.io/K1kEqCP.png',
    proxyUrl: '',
    tags: ['utility', 'web-access'],
    featured: false,
  },
  {
    id: '8',
    title: 'Waves',
    description: 'Surf the web freely with this powerful and lightweight proxy.',
    imageUrl: 'https://iili.io/K1kOug2.md.png',
    proxyUrl: 'https://waves.lat.cdn.cloudflare.net/',
    tags: ['utility', 'lightweight'],
    featured: false,
  },
  {
    id: '9',
    title: 'Utopia',
    description: 'A gateway to a perfect, unrestricted internet experience.',
    imageUrl: 'https://iili.io/K1kSDRp.png',
    proxyUrl: 'https://ut.blox.im/',
    tags: ['privacy', 'unblocker'],
    featured: false,
  },
  {
    id: '10',
    title: 'Emerald',
    description: 'A valuable tool for secure and private web browsing.',
    imageUrl: 'https://iili.io/K1km9KQ.png',
    proxyUrl: 'https://emerald.education.app.tc/',
    tags: ['security', 'utility'],
    featured: false,
  },
];
